# Generated by Django 6.1.1 on 2026-10-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='humidity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='smoke',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='temperature',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
